import { InlineKeyboard } from "grammy";
import { isAdmin } from "../services/admin.js";

export async function handleHelp(ctx) {
  const lines = [
    "🏦 *Magpie Help*",
    "",
    "*Navigation*",
    "/home — main menu",
    "/help — this page",
    "",
    "*Account*",
    "/me — wallet, tier, stats, referral code",
    "/deposit — show your deposit address",
    "/notify — manage notifications + auto-repay",
    "",
    "*Loans*",
    "/supported — accepted collateral with live prices",
    "/simulate <symbol> <amount> [tier] — preview a loan",
    "/borrow — take out a SOL loan",
    "/reborrow — quick re-borrow (same token + tier as last loan)",
    "/positions — active loans + live health (alias: /loans)",
    "/tx <sig> — quick lookup of any Solana tx",
    "/walletlookup <pubkey> — Magpie footprint of any wallet (rep check)",
    "/repay — repay and reclaim collateral",
    "/partialrepay — pay down part of a loan",
    "/topup — add collateral (improves health, no fee)",
    "/extend — extend a loan (tier fee: 3%/2%/1.5%)",
    "/history — last 10 loans",
    "/price <symbol|mint> — oracle price + max loan per tier",
    "",
    "*Wallet*",
    "/wallet — show your deposit address",
    "/deposit — same as /wallet",
    "/import — import an existing Solana wallet (advanced)",
    "/withdraw — send SOL or tokens out",
    "/export — export your private key (⚠️ custodial)",
    "",
    "*Credit & Risk*",
    "/credit — view your 300-850 credit score",
    "/risk <symbol> — AI risk assessment for a token",
    "",
    "*Earn*",
    "/refer — earn 5% of friends' loan fees (lifetime, paid in SOL)",
    "/holders — $MAGPIE holders earn 10% of all fees pro-rata (weekly distribution)",
    "",
    "*Marketplace*",
    "/lend — lending marketplace (create pools, deposit, browse)",
    "",
    "*Tokens*",
    "/submit <mint|symbol> — submit a token for collateral approval",
    "",
    "*Stats*",
    "/stats — protocol-wide stats",
    "",
    "*Support*",
    "/support — diagnose a loan, check a tx, or message the team",
    "/mytickets — your support history",
    "",
    "*Site*",
    "/site — open magpie.capital (does almost everything this bot does)",
    "/link <code> — link a wallet connected on the site",
    "",
    "*Privacy & security*",
    "/privacy — what data we store + how to control it",
    "/security — single-screen security view + lock buttons",
    "/lock [hours] — emergency pause on site signed actions (24h default)",
    "/lock 0 — clear the lock",
    "/exportdata — DM you a JSON file of your account data",
    "/signedhistory — last 10 signed site actions on your account",
    "/testalert — fire a test security DM at yourself",
    "",
    "*How it works*",
    "1. Deposit memecoins to your Magpie wallet",
    "2. Pick a tier:  30%/2d · 25%/3d · 20%/7d",
    "3. Receive SOL instantly (Express 3%, Quick 2%, Standard 1.5% fee)",
    "4. Repay before due to reclaim your bag",
    "5. Miss the deadline or drop below 1.1x → liquidation",
  ];

  if (isAdmin(ctx.from?.id)) {
    lines.push(
      "",
      "*Admin*",
      "/pause, /resume — toggle new borrows",
      "/adminstatus — system overview",
      "/enablemint <mint> <symbol> <decimals> [name]",
      "/disablemint <symbol|mint>",
      "/broadcast <message> — DM everyone",
      "/reviewtokens — review auto-screened tokens",
      "/siteops — site-action telemetry (24h locks, withdraws, signed actions)",
      "/adminlock <user> [hours] — force-lock a user (DMs them)",
      "/adminunlock <user> — clear a user's lock (DMs them)",
      "/sitedisable [reason] — STOP every signed site endpoint (503)",
      "/siteenable — re-enable signed site endpoints",
      "/sitestate — show current global state",
      "/announce <msg> [expires:hours] — set dashboard banner (info)",
      "/announcewarn / /announcecrit — same, with severity",
      "/announceclear — remove the banner",
    );
  }

  const kb = new InlineKeyboard()
    .text("🏠 Home", "start:home")
    .text("💰 Borrow", "start:borrow")
    .text("📋 Wallet", "fallback:deposit");

  await ctx.reply(lines.join("\n"), { parse_mode: "Markdown", reply_markup: kb });
}
