import { AnchorProvider, Program, Wallet } from "@coral-xyz/anchor";
import { Keypair, PublicKey } from "@solana/web3.js";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import "dotenv/config";
import { connection } from "./connection.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const idlPath = path.join(__dirname, "idl", "magpie_lending.json");
const idl = JSON.parse(readFileSync(idlPath, "utf8"));
// V2 IDL — different account layout (no fee_wallet field on LendingPool;
// the V2 program enforces fee routing via the authority-signed borrow tx
// rather than a stored fee_wallet pubkey). Loading it lazily here so
// existing V1 callers don't pay the parse cost.
const idlPathV2 = path.join(__dirname, "idl", "magpie_lending_v2.json");
let _idlV2 = null;
function getV2Idl() {
  if (!_idlV2) _idlV2 = JSON.parse(readFileSync(idlPathV2, "utf8"));
  return _idlV2;
}
// V3 IDL — RWA + memecoin dual-tier program live since 2026-06-13. V3's
// Loan account adds {collateral_value_at_start, vault_bump, category}
// after the V1 fields. Reading a V3 Loan with the V1 IDL silently
// mis-deserializes the appended fields and trips Borsh leftover-bytes
// errors during program.account.loan.fetch(). recordLoan in cosign-borrow
// fetches the Loan account post-submit, so it needs the matching IDL.
const idlPathV3 = path.join(__dirname, "idl", "magpie-v3.json");
let _idlV3 = null;
function getV3Idl() {
  if (!_idlV3) _idlV3 = JSON.parse(readFileSync(idlPathV3, "utf8"));
  return _idlV3;
}

// V4 IDL — adds in-vault auto-sell conversion via the new
// convert_collateral_slice instruction. Loan account extends V3's layout
// with current_collateral_amount, sol_proceeds_amount, auto_sells_fired.
// At pre-deploy / dev time the IDL file may not yet exist (the actual one
// is generated by `anchor build` against the V4 program). We resolve
// laziness identically to V2/V3 and fall back gracefully if the file is
// missing so existing flows keep working while V4 is being prepared.
const idlPathV4 = path.join(__dirname, "idl", "magpie-v4.json");
let _idlV4 = null;
function getV4Idl() {
  if (_idlV4) return _idlV4;
  try {
    _idlV4 = JSON.parse(readFileSync(idlPathV4, "utf8"));
  } catch {
    // V4 IDL not yet shipped — surface a clear error rather than silently
    // mis-deserializing a V4 account with V3 layout.
    throw new Error(
      "V4 IDL not found at src/solana/idl/magpie-v4.json. " +
      "Run `anchor build` against the magpie-v4 program and commit the generated IDL.",
    );
  }
  return _idlV4;
}

export const PROGRAM_ID = new PublicKey(
  process.env.PROGRAM_ID || idl.address,
);

// v2 program (RWA-capable; newer anchor-spl with PausableConfig + ScaledUiAmount
// support). Only set in env once v2 is deployed + validated. Until then, every
// borrow routes to v1 — RWA mints remain disabled in DB so no user can hit
// a not-yet-routable path.
export const PROGRAM_ID_V2 = process.env.PROGRAM_ID_V2
  ? new PublicKey(process.env.PROGRAM_ID_V2)
  : null;

// v3 = on-chain TWAP memecoin program. Only routable when BOTH:
//   - PROGRAM_ID_V3 is set (program deployed to mainnet)
//   - ROUTE_MEMECOINS_TO_V3=true (operator flipped the switch)
// Default behavior: memecoin borrows continue to route to v1, identical
// to today. Flipping the env routes NEW borrows to v3; v1 loans already
// open continue to repay/extend/liquidate via v1 because chooseProgramIdForLoan
// reads loans.program_id from the DB.
export const PROGRAM_ID_V3 = process.env.PROGRAM_ID_V3
  ? new PublicKey(process.env.PROGRAM_ID_V3)
  : null;
const ROUTE_MEMECOINS_TO_V3 = process.env.ROUTE_MEMECOINS_TO_V3 === "true";
// 2026-06-14: when V3 launches with the genuine 50/60/70% RWA tier ladder,
// flip this to "true" to route NEW RWA borrows to V3 instead of V2.
// Existing V2 RWA loans continue to serve from V2 because each loan
// row stores its own program_id (loans.program_id), so repay/extend/
// liquidate paths are program-loyal — they don't read this flag.
const ROUTE_RWA_TO_V3 = process.env.ROUTE_RWA_TO_V3 === "true";

// v4 = in-vault auto-sell program. New convert_collateral_slice instruction
// lets the engine swap a slice of SPL collateral to SOL and store the SOL
// in the loan vault, with the loan staying ACTIVE. Same dual-tier ladder
// as V3 (memecoin 30/25/20% + RWA 50/60/70% LTV). Routable when BOTH:
//   - PROGRAM_ID_V4 is set (deployed to mainnet)
//   - the relevant ROUTE_*_TO_V4=true flag is flipped
// When V4 is enabled, it supersedes V3 for new borrows. Existing V1/V2/V3
// loans continue to repay/extend/liquidate via their original program
// because each loan row stores its own program_id.
export const PROGRAM_ID_V4 = process.env.PROGRAM_ID_V4
  ? new PublicKey(process.env.PROGRAM_ID_V4)
  : null;
const ROUTE_MEMECOINS_TO_V4 = process.env.ROUTE_MEMECOINS_TO_V4 === "true";
const ROUTE_RWA_TO_V4 = process.env.ROUTE_RWA_TO_V4 === "true";

// Categories that should route to v2 once it's deployed. Source of truth
// for the category vocabulary lives in supported_mints.category — keep in
// sync with isRwa() in token-screener.js.
const RWA_CATEGORIES = new Set(["stock", "etf", "metal"]);

/**
 * The v2 pool is RWA-ONLY. Anything that isn't a tokenized real-world
 * asset (stock/etf/metal) MUST route to v1. The check is symmetric:
 *   v2 ⇔ category ∈ RWA_CATEGORIES
 *
 * 2026-06-07: hard-coded after the $FATHER incident, where a memecoin
 * misclassified as "stock" routed to v2 and bypassed memecoin-only
 * defenses. If you ever add a non-RWA category that should route to
 * v2, deploy a separate program for it — do NOT broaden this set.
 */
export function isRwaCategory(category) {
  return RWA_CATEGORIES.has(category);
}

/**
 * Pick the program ID for a NEW borrow.
 *
 * **V4-exclusive exits model (2026-06-15):** if the user is arming any
 * exit (TP / SL / trailing / bracket / ladder) as part of the borrow
 * flow, the loan MUST go to V4 — that's the only pool whose engine fire
 * path keeps the loan ACTIVE and accumulates SOL inside the per-loan
 * vault via convert_collateral_slice. V1/V2/V3 cannot service exits
 * going forward.
 *
 * If no exit is being armed, regular category routing applies:
 *   RWA (stock/etf/metal) → v3 (if configured AND ROUTE_RWA_TO_V3=true)
 *                          otherwise v2 (if configured), otherwise v1
 *   memecoin (default)    → v3 (if configured AND ROUTE_MEMECOINS_TO_V3=true)
 *                          otherwise v1
 *
 *   chooseProgramId(category)                          — plain borrow
 *   chooseProgramId(category, { hasExitArming: true }) — exit-armed borrow
 *
 * Existing loans repay against THEIR original program (loans.program_id);
 * this routing only governs NEW borrows.
 *
 * Throws when hasExitArming=true but PROGRAM_ID_V4 isn't deployed — the
 * caller MUST refuse the borrow up the stack and tell the user exits
 * aren't available right now. Silently falling back to V1/V3 would
 * promise the user an in-vault exit and not deliver it.
 *
 * Fail-safe for the no-exit path: when in doubt, return v1.
 */
export function chooseProgramId(category, opts = {}) {
  const { hasExitArming = false, isToken2022 = false } = opts;
  if (hasExitArming) {
    if (!PROGRAM_ID_V4) {
      throw new Error(
        "EXIT_ARMING_REQUIRES_V4: exit-armed borrow requested but PROGRAM_ID_V4 is not configured. " +
        "Either complete the V4 deploy / env setup, or build a plain borrow without an exit.",
      );
    }
    // V4 IN-VAULT THESIS IS NON-NEGOTIABLE (operator-mandated 2026-06-15 PM,
    // feedback_v4_in_vault_thesis_non_negotiable.md). When the currently-
    // deployed V4 program version has a bug specific to Token-2022 collateral
    // (operator hit it on loan id=763 SPCX V4: `incorrect program id for
    // instruction` at RepayLoan), the answer is NOT to route around it via
    // V3's legacy fire-and-close model — V3's model violates the V4 thesis
    // by sending proceeds to the user wallet on fire. The answer is to
    // BLOCK the borrow with a clear message until V4.x ships with the fix.
    if (isToken2022) {
      throw new Error(
        "TOKEN2022_EXIT_ARMING_TEMPORARILY_BLOCKED: Auto-sells on Token-2022 " +
        "collateral (tokenized stocks, ETFs, metals) are temporarily paused " +
        "while V4 is patched for in-vault repay handling. Two options: " +
        "(a) borrow without an auto-sell attached, or " +
        "(b) use a classic-SPL memecoin collateral if you need the exit feature. " +
        "We'll re-enable Token-2022 exits the moment the V4 patch ships at a fresh " +
        "program ID — existing loans won't be affected.",
      );
    }
    return PROGRAM_ID_V4;
  }
  if (RWA_CATEGORIES.has(category)) {
    if (PROGRAM_ID_V3 && ROUTE_RWA_TO_V3) return PROGRAM_ID_V3;
    if (PROGRAM_ID_V2) return PROGRAM_ID_V2;
    return PROGRAM_ID;
  }
  // Non-RWA path
  if (PROGRAM_ID_V3 && ROUTE_MEMECOINS_TO_V3) return PROGRAM_ID_V3;
  return PROGRAM_ID;
}

/**
 * Backwards-compatible shim — pre-2026-06-15 callers that don't know
 * about exit arming still call this. They get the plain-borrow routing,
 * which is correct because if the caller didn't pass `hasExitArming`,
 * they aren't in an exit-arming flow.
 *
 * New callers should use chooseProgramId(category, { hasExitArming })
 * directly so the exit-aware routing engages.
 */
export function chooseProgramIdForCategory(category) {
  return chooseProgramId(category, { hasExitArming: false });
}

/**
 * Defense-in-depth assertion. Throws if a v2 program ID is paired with a
 * non-RWA category — that should be impossible if the routing logic is
 * correct, but catching it here means a corrupt DB row, a manual
 * /enablemint typo, or future code drift can't silently put a memecoin
 * into the RWA pool. Callers in the borrow flow MUST call this.
 */
export function assertProgramMatchesCategory(programId, category) {
  if (!programId) return;
  const isRwa = RWA_CATEGORIES.has(category);
  const routesToV2 = PROGRAM_ID_V2 && programId.equals(PROGRAM_ID_V2);
  const routesToV3 = PROGRAM_ID_V3 && programId.equals(PROGRAM_ID_V3);
  const routesToV4 = PROGRAM_ID_V4 && programId.equals(PROGRAM_ID_V4);
  const routesToV1 = !routesToV2 && !routesToV3 && !routesToV4; // default

  // Pool semantics as of 2026-06-13 (V3 launch):
  //   V1: memecoin-only (legacy memecoin lending)
  //   V2: RWA-only (legacy RWA lending; existing loans still serviced)
  //   V3: BOTH memecoin AND RWA (dual-tier program — RWA gets the
  //       50/60/70% ladder, memecoin keeps 30/25/20%)
  //
  // Invalid combinations (hard fail):
  //   V2 + memecoin (the $FATHER class of vulnerability — never)
  //   V1 + RWA      (RWAs must go to V2 or V3, not V1)
  //
  // Pre-2026-06-13 there was a third "V3 + RWA" hard-stop here because
  // V3 used to be memecoin-only. The 2026-06-14 RWA route-flip
  // (PR #225 + ROUTE_RWA_TO_V3=true) made V3 the active RWA target,
  // so that assertion is now stale + actively wrong — it was breaking
  // /borrow for tokenized stocks. Removed below.

  if (routesToV2 && !isRwa) {
    throw new Error(
      `Program/category mismatch: V2 pool requires RWA category, got "${category ?? "<null>"}". ` +
        `Memecoins must never route to V2. This is a hard safety stop — review the mint's ` +
        `supported_mints.category column.`,
    );
  }
  if (routesToV1 && isRwa) {
    throw new Error(
      `Program/category mismatch: category "${category}" is RWA but program routes to V1. ` +
        `RWAs belong in V2 (legacy) or V3 — check chooseProgramIdForCategory + the routing env flag.`,
    );
  }
  // V3 + RWA: VALID — V3 has the new RWA ladder.
  // V3 + memecoin: VALID — V3 dual-tier supports memecoin too.
  // V4 + RWA: VALID — V4 dual-tier with in-vault auto-sell.
  // V4 + memecoin: VALID — V4 dual-tier with in-vault auto-sell.
  // V1 + memecoin: VALID — default path.
  // V2 + RWA: VALID — legacy RWA pool.
}

/**
 * Pick the program for an EXISTING loan (repay/extend/topup/liquidate).
 * Authoritative source is the loans.program_id column populated at borrow
 * time. Older rows backfilled to v1 — handled by COALESCE default.
 */
export function chooseProgramIdForLoan(loanRow) {
  if (loanRow?.program_id) return new PublicKey(loanRow.program_id);
  return PROGRAM_ID;
}

/**
 * Build a read-only Anchor Program for queries that don't need a signer.
 * Pass `programId` to target v2; defaults to v1.
 */
export function getReadOnlyProgram(programId = PROGRAM_ID) {
  const dummyKp = Keypair.generate();
  const provider = new AnchorProvider(connection, new Wallet(dummyKp), {
    commitment: "confirmed",
  });
  // Pick the matching IDL: V1 (legacy), V2 (authority-routed fees),
  // V3 (RWA + memecoin dual ladder, appended Loan fields). Using the
  // wrong IDL silently mis-deserializes every field past the layout
  // divergence — caught the missing V2 fee_wallet during 2026-06-12
  // and the V3 Loan size mismatch during 2026-06-14.
  let useIdl = idl;
  if (PROGRAM_ID_V4 && programId.equals(PROGRAM_ID_V4)) {
    useIdl = getV4Idl();
  } else if (PROGRAM_ID_V3 && programId.equals(PROGRAM_ID_V3)) {
    useIdl = getV3Idl();
  } else if (PROGRAM_ID_V2 && programId.equals(PROGRAM_ID_V2)) {
    useIdl = getV2Idl();
  }
  return new Program({ ...useIdl, address: programId.toBase58() }, provider);
}

/**
 * Build an Anchor Program with a specific signer (e.g. a user's custodial keypair).
 * Pass `programId` to target v2; defaults to v1.
 */
export function getProgramForSigner(signerKeypair, programId = PROGRAM_ID) {
  const provider = new AnchorProvider(connection, new Wallet(signerKeypair), {
    commitment: "confirmed",
  });
  // Pick the matching IDL per programId. V3's request_and_fund_loan has
  // ONE EXTRA u8 arg vs V1/V2 (category byte). If we build the program
  // object with V1 IDL but target V3, the borrow flow's 5-arg call
  // throws "provided too many arguments ... expecting:
  // collateralAmount,loanOption,collateralValue,loanId" — caught
  // 2026-06-14 on the SPCX TG borrow path. Mirrors the same IDL
  // selection getReadOnlyProgram does above.
  let useIdl = idl;
  if (PROGRAM_ID_V4 && programId.equals(PROGRAM_ID_V4)) {
    useIdl = getV4Idl();
  } else if (PROGRAM_ID_V3 && programId.equals(PROGRAM_ID_V3)) {
    useIdl = getV3Idl();
  } else if (PROGRAM_ID_V2 && programId.equals(PROGRAM_ID_V2)) {
    useIdl = getV2Idl();
  }
  return new Program({ ...useIdl, address: programId.toBase58() }, provider);
}
